name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Call tool with parameters...
        2. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages if applicable.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code to reproduce the issue
      render: python
      placeholder: |
        from vertex.tools import solve_lp
        
        result = solve_lp(...)

  - type: input
    id: version
    attributes:
      label: Vertex Version
      description: What version of Vertex are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Mode
      description: How are you running Vertex?
      options:
        - Stdio (Claude Desktop)
        - HTTP (Docker)
        - HTTP (Direct)
        - Other
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: "3.13"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Ubuntu 22.04"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Include any relevant log output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
